### ISSUE TITLE
[feature] Preview/view markdown documents 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/editor#29]
If the file is a filename.md document then the preview is possible.
This should be the standard way for a teacher to add to a document to a course.
Under the editor it's markdown when it's an asset it in web mode.

**Comment by mciissee** [comment]
This is already possible <img width="1119" alt="Capture d’écran 2020-05-15 à 14 16 30" src="https://user-images.githubusercontent.com/30326262/82049540-c7e35480-96b6-11ea-874b-27e9eae1907d.png">

**Comment by nimdanor** [comment]
thanks
